insert into Division (name) values ('Ayeyarwady Region');
insert into Division (name) values ('Bago Region');
insert into Division (name) values ('Chin State');
insert into Division (name) values ('Kachin State');
insert into Division (name) values ('Kayah State');
insert into Division (name) values ('Kayin State');
insert into Division (name) values ('Magway Region');
insert into Division (name) values ('Mandalay Region');
insert into Division (name) values ('Mon State');
insert into Division (name) values ('Rakhine State');
insert into Division (name) values ('Shan State');
insert into Division (name) values ('Sagaing Region');
insert into Division (name) values ('Tanintharyi Region');
insert into Division (name) values ('Yangon Region');
insert into Division (name) values ('Naypyidaw Union Territory');

-- Ayeyawady
insert into Township (division_id, name) values (1, 'Hinthada Township');
insert into Township (division_id, name) values (1, 'Lemyethna Township');
insert into Township (division_id, name) values (1, 'Zalun Township');
insert into Township (division_id, name) values (1, 'Ithapyu Township');
insert into Township (division_id, name) values (1, 'Labutta Township');
insert into Township (division_id, name) values (1, 'Mawlamyinegyun Township');
insert into Township (division_id, name) values (1, 'Kyonmanage Township');
insert into Township (division_id, name) values (1, 'Pyinsalu Township');
insert into Township (division_id, name) values (1, 'Danubyu Township');
insert into Township (division_id, name) values (1, 'Ma-ubin Township');
insert into Township (division_id, name) values (1, 'Nyaungdon Township');
insert into Township (division_id, name) values (1, 'Pantanaw Township');
insert into Township (division_id, name) values (1, 'Einme Township');
insert into Township (division_id, name) values (1, 'Myaungmya Township');
insert into Township (division_id, name) values (1, 'Wakema Township');
insert into Township (division_id, name) values (1, 'Shwelaung Township');
insert into Township (division_id, name) values (1, 'Kangyidaunk Township');
insert into Township (division_id, name) values (1, 'Ngapudaw Township');
insert into Township (division_id, name) values (1, 'Pathein Township');
insert into Township (division_id, name) values (1, 'Thabaung Township');
insert into Township (division_id, name) values (1, 'Chaungtha Township');
insert into Township (division_id, name) values (1, 'Hainggyi Township');
insert into Township (division_id, name) values (1, 'Ngayokekaung Township');
insert into Township (division_id, name) values (1, 'Ngwesaung Township');
insert into Township (division_id, name) values (1, 'Bogale Township');
insert into Township (division_id, name) values (1, 'Dedaye Township');
insert into Township (division_id, name) values (1, 'Kyaiklat Township');
insert into Township (division_id, name) values (1, 'Pyapon Township');
insert into Township (division_id, name) values (1, 'Ahmar Township');
insert into Township (division_id, name) values (1, 'Kyaunggon Township');
insert into Township (division_id, name) values (1, 'Kyonpyaw Township');
insert into Township (division_id, name) values (1, 'Yekyi Township');
insert into Township (division_id, name) values (1, 'Ahtaung Township');
insert into Township (division_id, name) values (1, 'Ngathinechaung Township');
insert into Township (division_id, name) values (1, 'Ingapu Township');
insert into Township (division_id, name) values (1, 'Kyangin Township');
insert into Township (division_id, name) values (1, 'Myanaung Township');
insert into Township (division_id, name) values (1, 'Kanaung Township');


-- Bago
insert into Township (division_id, name) values (2, 'Bago Township');
insert into Township (division_id, name) values (2, 'Daik-U Township');
insert into Township (division_id, name) values (2, 'Kawa Township');
insert into Township (division_id, name) values (2, 'Nyaunglebin Township');
insert into Township (division_id, name) values (2, 'Shwegyin Township');
insert into Township (division_id, name) values (2, 'Thanatpin Township');
insert into Township (division_id, name) values (2, 'Waw Township');
insert into Township (division_id, name) values (2, 'Kyauktaga Township');
insert into Township (division_id, name) values (2, 'Kyaukkyi Township');
insert into Township (division_id, name) values (2, 'Oktwin Township');
insert into Township (division_id, name) values (2, 'Pyu Township');
insert into Township (division_id, name) values (2, 'Tantabin Township');
insert into Township (division_id, name) values (2, 'Taungoo Township');
insert into Township (division_id, name) values (2, 'Yedashe Township');
insert into Township (division_id, name) values (2, 'Pandaung Township');
insert into Township (division_id, name) values (2, 'Paukkaung Township');
insert into Township (division_id, name) values (2, 'Paungde Township');
insert into Township (division_id, name) values (2, 'Pyay Township');
insert into Township (division_id, name) values (2, 'Shwedaung Township');
insert into Township (division_id, name) values (2, 'Thegon Township');
insert into Township (division_id, name) values (2, 'Gyobingauk Township');
insert into Township (division_id, name) values (2, 'Letpadan Township');
insert into Township (division_id, name) values (2, 'Minhla Township');
insert into Township (division_id, name) values (2, 'Monyo Township');
insert into Township (division_id, name) values (2, 'Okpho Township');
insert into Township (division_id, name) values (2, 'Tharrawaddy Township');
insert into Township (division_id, name) values (2, 'Nattalin Township');
insert into Township (division_id, name) values (2, 'Zigon Township');

-- Chin
insert into Township (division_id, name) values (3, 'Falam Township');
insert into Township (division_id, name) values (3, 'Tiddim Township');
insert into Township (division_id, name) values (3, 'Ton Zang Township');
insert into Township (division_id, name) values (3, 'Hakha Township');
insert into Township (division_id, name) values (3, 'Htantlang Township');
insert into Township (division_id, name) values (3, 'Matupi Township');
insert into Township (division_id, name) values (3, 'Paletwa Township');
insert into Township (division_id, name) values (3, 'Kanpetlet Township');
insert into Township (division_id, name) values (3, 'Mindat Township');

-- Kachin
insert into Township (division_id, name) values (4, 'Bhamo Township');
insert into Township (division_id, name) values (4, 'Mansi Township');
insert into Township (division_id, name) values (4, 'Momauk Township');
insert into Township (division_id, name) values (4, 'Shwegu Township');
insert into Township (division_id, name) values (4, 'Mogaung Township');
insert into Township (division_id, name) values (4, 'Mohnyin Township');
insert into Township (division_id, name) values (4, 'Phakant Township');
insert into Township (division_id, name) values (4, 'Chipwi Township');
insert into Township (division_id, name) values (4, 'Hsawlaw Township');
insert into Township (division_id, name) values (4, 'Injangyang Township');
insert into Township (division_id, name) values (4, 'Myitkyina Township');
insert into Township (division_id, name) values (4, 'Tanai Township');
insert into Township (division_id, name) values (4, 'Waingmaw Township');
insert into Township (division_id, name) values (4, 'Kawnglanghpu Township');
insert into Township (division_id, name) values (4, 'Machanbaw Township');
insert into Township (division_id, name) values (4, 'Nogmung Township');
insert into Township (division_id, name) values (4, 'Putao Township');
insert into Township (division_id, name) values (4, 'Sumprabum Township');

-- Kayah
insert into Township (division_id, name) values (5, 'Bawlakhe Township');
insert into Township (division_id, name) values (5, 'Hpasawng Township');
insert into Township (division_id, name) values (5, 'Mese Township');
insert into Township (division_id, name) values (5, 'Ywathit Subtownship');
insert into Township (division_id, name) values (5, 'Demoso Township');
insert into Township (division_id, name) values (5, 'Hpruso Township');
insert into Township (division_id, name) values (5, 'Loikaw Township');
insert into Township (division_id, name) values (5, 'Shadaw Township');

-- Kayin
insert into Township (division_id, name) values (6, 'Hlaingbwe Township');
insert into Township (division_id, name) values (6, 'Hpa-an Township');
insert into Township (division_id, name) values (6, 'Thandaunggyi Township');
insert into Township (division_id, name) values (6, 'Hpapun Township');
insert into Township (division_id, name) values (6, 'Kawkareik Township');
insert into Township (division_id, name) values (6, 'Kyain Seikgyi Township');
insert into Township (division_id, name) values (6, 'Myawaddy Township');

-- Magway
insert into Township (division_id, name) values (7, 'Gangaw Township');
insert into Township (division_id, name) values (7, 'Saw Township');
insert into Township (division_id, name) values (7, 'Htilin Township');
insert into Township (division_id, name) values (7, 'Kyaukhtu Subtownship');
insert into Township (division_id, name) values (7, 'Chauk Township');
insert into Township (division_id, name) values (7, 'Magway Township');
insert into Township (division_id, name) values (7, 'Myothit Township');
insert into Township (division_id, name) values (7, 'Natmauk Township');
insert into Township (division_id, name) values (7, 'Taungdwingyi Township');
insert into Township (division_id, name) values (7, 'Yenangyaung Township');
insert into Township (division_id, name) values (7, 'Minbu Township');
insert into Township (division_id, name) values (7, 'Ngape Township');
insert into Township (division_id, name) values (7, 'Pwintbyu Township');
insert into Township (division_id, name) values (7, 'Salin Township');
insert into Township (division_id, name) values (7, 'Sidoktaya Township');
insert into Township (division_id, name) values (7, 'Myaing Township');
insert into Township (division_id, name) values (7, 'Pakokku Township');
insert into Township (division_id, name) values (7, 'Pauk Township');
insert into Township (division_id, name) values (7, 'Seikphyu Township');
insert into Township (division_id, name) values (7, 'Yesagyo Township');
insert into Township (division_id, name) values (7, 'Aunglan Township');
insert into Township (division_id, name) values (7, 'Kamma Township');
insert into Township (division_id, name) values (7, 'Mindon Township');
insert into Township (division_id, name) values (7, 'Minhla Township');
insert into Township (division_id, name) values (7, 'Sinbaungwe Township');
insert into Township (division_id, name) values (7, 'Thayet Township');

-- Mandalay
insert into Township (division_id, name) values (8, 'Kyaukse Township');
insert into Township (division_id, name) values (8, 'Myittha Township');
insert into Township (division_id, name) values (8, 'Sintgaing Township');
insert into Township (division_id, name) values (8, 'Tada-U Township');
insert into Township (division_id, name) values (8, 'Amarapura Township');
insert into Township (division_id, name) values (8, 'Aungmyethazan Township');
insert into Township (division_id, name) values (8, 'Chanayethazan Township');
insert into Township (division_id, name) values (8, 'Chanmyathazi Township');
insert into Township (division_id, name) values (8, 'Maha Aungmye Township');
insert into Township (division_id, name) values (8, 'Patheingyi Township');
insert into Township (division_id, name) values (8, 'Pyigyidagun Township');
insert into Township (division_id, name) values (8, 'Mahlaing Township');
insert into Township (division_id, name) values (8, 'Meiktila Township');
insert into Township (division_id, name) values (8, 'Thazi Township');
insert into Township (division_id, name) values (8, 'Wundwin Township');
insert into Township (division_id, name) values (8, 'Myingyan Township');
insert into Township (division_id, name) values (8, 'Natogyi Township');
insert into Township (division_id, name) values (8, 'Ngazun Township');
insert into Township (division_id, name) values (8, 'Taungtha Township');
insert into Township (division_id, name) values (8, 'Kyaukpadaung Township');
insert into Township (division_id, name) values (8, 'Nyaung-U Township');
insert into Township (division_id, name) values (8, 'Ngathayauk Subtownship');
insert into Township (division_id, name) values (8, 'Madaya Township');
insert into Township (division_id, name) values (8, 'Mogok Township');
insert into Township (division_id, name) values (8, 'Pyinoolwin Township');
insert into Township (division_id, name) values (8, 'Singu Township');
insert into Township (division_id, name) values (8, 'Thabeikkyin Township');
insert into Township (division_id, name) values (8, 'Pyawbwe Township');
insert into Township (division_id, name) values (8, 'Yamethin Townshi');

-- Mon
insert into Township (division_id, name) values (9, 'Chaungzon Township');
insert into Township (division_id, name) values (9, 'Kyaikmaraw Township');
insert into Township (division_id, name) values (9, 'Mawlamyine Township');
insert into Township (division_id, name) values (9, 'Mudon Township');
insert into Township (division_id, name) values (9, 'Thanbyuzayat Township');
insert into Township (division_id, name) values (9, 'Ye Township');
insert into Township (division_id, name) values (9, 'Bilin Township');
insert into Township (division_id, name) values (9, 'Kyaikto Township');
insert into Township (division_id, name) values (9, 'Paung Township');
insert into Township (division_id, name) values (9, 'Thaton Township');

-- Rakhine
insert into Township (division_id, name) values (10, 'Ann Township');
insert into Township (division_id, name) values (10, 'Kyaukpyu Township');
insert into Township (division_id, name) values (10, 'Manaung Township');
insert into Township (division_id, name) values (10, 'Ramree Township');
insert into Township (division_id, name) values (10, 'Buthidaung Township');
insert into Township (division_id, name) values (10, 'Maungdaw Township');
insert into Township (division_id, name) values (10, 'Pauktaw Township');
insert into Township (division_id, name) values (10, 'Ponnagyun Township');
insert into Township (division_id, name) values (10, 'Rathedaung Township');
insert into Township (division_id, name) values (10, 'Sittwe Township');
insert into Township (division_id, name) values (10, 'Thandwe Township');
insert into Township (division_id, name) values (10, 'Toungup Township');
insert into Township (division_id, name) values (10, 'Gwa Township');
insert into Township (division_id, name) values (10, 'Maei Subtownship');
insert into Township (division_id, name) values (10, 'Kyeintali Subtownship');
insert into Township (division_id, name) values (10, 'Kyauktaw Township');
insert into Township (division_id, name) values (10, 'Minbya Township');
insert into Township (division_id, name) values (10, 'Mrauk-U Township');
insert into Township (division_id, name) values (10, 'Myebon Township');

-- Shan
insert into Township (division_id, name) values (11, 'Kengtung Township');
insert into Township (division_id, name) values (11, 'Mong Khet Township');
insert into Township (division_id, name) values (11, 'Mong La Township (SR4)');
insert into Township (division_id, name) values (11, 'Mong Yang Township');
insert into Township (division_id, name) values (11, 'Mine Pauk Subtownship');
insert into Township (division_id, name) values (11, 'Minelar Subtownship');
insert into Township (division_id, name) values (11, 'Mong Hpayak Township (SR4)');
insert into Township (division_id, name) values (11, 'Mong Yawng Township');
insert into Township (division_id, name) values (11, 'Mineyu Subtownship');
insert into Township (division_id, name) values (11, 'Mong Hsat Township');
insert into Township (division_id, name) values (11, 'Mong Ping Township');
insert into Township (division_id, name) values (11, 'Mong Tong Township');
insert into Township (division_id, name) values (11, 'Minekoke Subtownship');
insert into Township (division_id, name) values (11, 'Monehta Subtownship');
insert into Township (division_id, name) values (11, 'Ponparkyin Subtownship');
insert into Township (division_id, name) values (11, 'Tontar Subtownship');;
insert into Township (division_id, name) values (11, 'Tachileik Township')
insert into Township (division_id, name) values (11, 'Kyaing Lap Subtownship (Kenglap)');
insert into Township (division_id, name) values (11, 'Talay Subtownship');
insert into Township (division_id, name) values (11, 'Kunlong Township');
insert into Township (division_id, name) values (11, 'Hsipaw Township');
insert into Township (division_id, name) values (11, 'Kyaukme Township');
insert into Township (division_id, name) values (11, 'Namtu Township');
insert into Township (division_id, name) values (11, 'Nawnghkio Township');
insert into Township (division_id, name) values (11, 'Minelon Subtownship');
insert into Township (division_id, name) values (11, 'Minengaw Subtownship');
insert into Township (division_id, name) values (11, 'Hseni Township');
insert into Township (division_id, name) values (11, 'Lashio Township');
insert into Township (division_id, name) values (11, 'Mongyai Township');
insert into Township (division_id, name) values (11, 'Tangyan Township');
insert into Township (division_id, name) values (11, 'see Kokang Self-Administered Zone');
insert into Township (division_id, name) values (11, 'Kutkai Township');
insert into Township (division_id, name) values (11, 'Mu Se Township');
insert into Township (division_id, name) values (11, 'Nanhkan Township');
insert into Township (division_id, name) values (11, 'Manhero Subtownship');
insert into Township (division_id, name) values (11, 'Monekoe Subtownship');
insert into Township (division_id, name) values (11, 'Pansai Subtownship (Kyu-kok)');
insert into Township (division_id, name) values (11, 'Tamoenye Subtownship');
insert into Township (division_id, name) values (11, 'see Wa Self-Administered Division');
insert into Township (division_id, name) values (11, 'see Wa Self-Administered Division');
insert into Township (division_id, name) values (11, 'Mabein Township');
insert into Township (division_id, name) values (11, 'Mongmit Township');
insert into Township (division_id, name) values (11, 'Laukkaing Township');
insert into Township (division_id, name) values (11, 'Konkyan Township');
insert into Township (division_id, name) values (11, 'Chinshwehaw Subtownship');
insert into Township (division_id, name) values (11, 'Mawhtike Subtownship');
insert into Township (division_id, name) values (11, 'Mantong Township1');
insert into Township (division_id, name) values (11, 'Namhsan Township1');
insert into Township (division_id, name) values (11, 'Hopang Township');
insert into Township (division_id, name) values (11, 'Mongmaw Township (Minemaw)');
insert into Township (division_id, name) values (11, 'Pangwaun Township (Panwine)');
insert into Township (division_id, name) values (11, 'Namtit Subtownship');
insert into Township (division_id, name) values (11, 'Panlong Subtownship');
insert into Township (division_id, name) values (11, 'Matman Township (Metman)');
insert into Township (division_id, name) values (11, 'Namphan Township (Naphang)');
insert into Township (division_id, name) values (11, 'Pangsang Township (Pan San)');
insert into Township (division_id, name) values (11, 'Man Kan Subtownship');
insert into Township (division_id, name) values (11, 'Langhko Township');
insert into Township (division_id, name) values (11, 'Mawkmai Township');
insert into Township (division_id, name) values (11, 'Mong Nai Township');
insert into Township (division_id, name) values (11, 'Mong Pan Township');
insert into Township (division_id, name) values (11, 'Homane Subtownship');
insert into Township (division_id, name) values (11, 'Kengtaung Subtownship');
insert into Township (division_id, name) values (11, 'Kunhing Township');
insert into Township (division_id, name) values (11, 'Kyethi Township');
insert into Township (division_id, name) values (11, 'Lai-Hka Township');
insert into Township (division_id, name) values (11, 'Loilen Township');
insert into Township (division_id, name) values (11, 'Mong Hsu Township');
insert into Township (division_id, name) values (11, 'Mong Kung Township');
insert into Township (division_id, name) values (11, 'Nansang Township');
insert into Township (division_id, name) values (11, 'Karli Subtownship');
insert into Township (division_id, name) values (11, 'Kholan Subtownship');
insert into Township (division_id, name) values (11, 'Minenaung Subtownship');
insert into Township (division_id, name) values (11, 'Minesan Subtownship');
insert into Township (division_id, name) values (11, 'Panglong Subtownship');
insert into Township (division_id, name) values (11, 'Kalaw Township');
insert into Township (division_id, name) values (11, 'Lawksawk Township');
insert into Township (division_id, name) values (11, 'Nyaungshwe Township');
insert into Township (division_id, name) values (11, 'Pekon Township');
insert into Township (division_id, name) values (11, 'Taunggyi Township');
insert into Township (division_id, name) values (11, 'Indaw Subtownship');
insert into Township (division_id, name) values (11, 'Kyauktalongyi Subtownship');
insert into Township (division_id, name) values (11, 'Naungtayar Subtownship');
insert into Township (division_id, name) values (11, 'Pindaya Township');
insert into Township (division_id, name) values (11, 'Ywangan Township');
insert into Township (division_id, name) values (11, 'Hopong Township');
insert into Township (division_id, name) values (11, 'Hsi Hseng Township');
insert into Township (division_id, name) values (11, 'Pinlaung Township');

-- Sagaing
insert into Township (division_id, name) values (12, 'Hkamti Township (Singkaling Hkamti)');
insert into Township (division_id, name) values (12, 'Homalin Township (Homalin)');
insert into Township (division_id, name) values (12, 'Kanbalu Township (Kanbalu)');
insert into Township (division_id, name) values (12, 'Kyunhla Township (Kyunhla)');
insert into Township (division_id, name) values (12, 'Taze Township (Taze)');
insert into Township (division_id, name) values (12, 'Ye-U Township (Ye-U)');
insert into Township (division_id, name) values (12, 'Kale Township (Kalaymyo)');
insert into Township (division_id, name) values (12, 'Kalewa Township (Kalewa)');
insert into Township (division_id, name) values (12, 'Mingin Township (Mingin)');
insert into Township (division_id, name) values (12, 'Banmauk Township (Banmauk)');
insert into Township (division_id, name) values (12, 'Indaw Township (Indaw)');
insert into Township (division_id, name) values (12, 'Katha Township (Katha)');
insert into Township (division_id, name) values (12, 'Kawlin Township (Kawlin)');
insert into Township (division_id, name) values (12, 'Pinlebu Township (Pinlebu)');
insert into Township (division_id, name) values (12, 'Htigyaing Township (Htigyaing)');
insert into Township (division_id, name) values (12, 'Wuntho Township (Wuntho)');
insert into Township (division_id, name) values (12, 'Mawlaik Township (Mawlaik)');
insert into Township (division_id, name) values (12, 'Paungbyin Township (Paungbyin)');
insert into Township (division_id, name) values (12, 'Ayadaw Township (Ayadaw)');
insert into Township (division_id, name) values (12, 'Budalin Township (Budalin)');
insert into Township (division_id, name) values (12, 'Chaung-U Township (Chaung-U)');
insert into Township (division_id, name) values (12, 'Monywa Township (Monywa)');
insert into Township (division_id, name) values (12, 'Myaung Township (Myaung)');
insert into Township (division_id, name) values (12, 'Myinmu Township (Myinmu)');
insert into Township (division_id, name) values (12, 'Sagaing Township (Sagaing)');
insert into Township (division_id, name) values (12, 'Khin-U Township (Khin-U)');
insert into Township (division_id, name) values (12, 'Shwebo Township (Shwebo)');
insert into Township (division_id, name) values (12, 'Wetlet Township (Wetlet)');
insert into Township (division_id, name) values (12, 'Tabayin Township (Tabayin)');
insert into Township (division_id, name) values (12, 'Tamu Township (Tamu)');
insert into Township (division_id, name) values (12, 'Kani Township (Kani)');
insert into Township (division_id, name) values (12, 'Pale Township (Pale)');
insert into Township (division_id, name) values (12, 'Salingyi Township (Salingyi)');
insert into Township (division_id, name) values (12, 'Yinmabin Township (Yinmabin)');
insert into Township (division_id, name) values (12, 'Lahe Township (Lahe)');
insert into Township (division_id, name) values (12, 'Leshi Township (Leshi)');
insert into Township (division_id, name) values (12, 'Nanyun Township (Nanyun)');

-- Tanintharyi
insert into Township (division_id, name) values (13, 'Dawei Township');
insert into Township (division_id, name) values (13, 'Launglon Township');
insert into Township (division_id, name) values (13, 'Thayetchaung Township');
insert into Township (division_id, name) values (13, 'Yebyu Township');
insert into Township (division_id, name) values (13, 'Kaleinaung Subtownship');
insert into Township (division_id, name) values (13, 'Myitta Subtownship');
insert into Township (division_id, name) values (13, 'Bokpyin Township');
insert into Township (division_id, name) values (13, 'Kawthaung Township');
insert into Township (division_id, name) values (13, 'Karathuri Subtownship');
insert into Township (division_id, name) values (13, 'Khamaukgyi Subtownship');
insert into Township (division_id, name) values (13, 'Pyigyimandaing Subtownship');
insert into Township (division_id, name) values (13, 'Kyunsu Township');
insert into Township (division_id, name) values (13, 'Myeik Township');
insert into Township (division_id, name) values (13, 'Palaw Township');
insert into Township (division_id, name) values (13, 'Tanintharyi Township');
insert into Township (division_id, name) values (13, 'Palauk Subtownship');

-- Yangon
insert into Township (division_id, name) values (14, 'Botataung Township');
insert into Township (division_id, name) values (14, 'Dagon Seikkan Township');
insert into Township (division_id, name) values (14, 'East Dagon Township');
insert into Township (division_id, name) values (14, 'North Dagon Township');
insert into Township (division_id, name) values (14, 'North Okkalapa Township');
insert into Township (division_id, name) values (14, 'Pazundaung Township');
insert into Township (division_id, name) values (14, 'South Dagon Township');
insert into Township (division_id, name) values (14, 'South Okkalapa Township');
insert into Township (division_id, name) values (14, 'Thingangyun Township');
insert into Township (division_id, name) values (14, 'Dawbon Township1');
insert into Township (division_id, name) values (14, 'Mingala Taungnyunt Township1');
insert into Township (division_id, name) values (14, 'Tamwe Township1');
insert into Township (division_id, name) values (14, 'Thaketa Township1');
insert into Township (division_id, name) values (14, 'Yankin Township1');
insert into Township (division_id, name) values (14, 'Hlaingthaya Township');
insert into Township (division_id, name) values (14, 'Insein Township');
insert into Township (division_id, name) values (14, 'Mingaladon Township');
insert into Township (division_id, name) values (14, 'Shwepyitha Township');
insert into Township (division_id, name) values (14, 'Hlegu Township');
insert into Township (division_id, name) values (14, 'Hmawbi Township');
insert into Township (division_id, name) values (14, 'Htantabin Township');
insert into Township (division_id, name) values (14, 'Taikkyi Township');
insert into Township (division_id, name) values (14, 'Dala Township');
insert into Township (division_id, name) values (14, 'Seikkyi Kanaungto Township');
insert into Township (division_id, name) values (14, 'Cocokyun Township');
insert into Township (division_id, name) values (14, 'Kawhmu Township');
insert into Township (division_id, name) values (14, 'Kayan Township');
insert into Township (division_id, name) values (14, 'Kungyangon Township');
insert into Township (division_id, name) values (14, 'Kyauktan Township');
insert into Township (division_id, name) values (14, 'Thanlyin Township');
insert into Township (division_id, name) values (14, 'Thongwa Township');
insert into Township (division_id, name) values (14, 'Twante Township');
insert into Township (division_id, name) values (14, 'Tada Subtownship');
insert into Township (division_id, name) values (14, 'Ahlon Township');
insert into Township (division_id, name) values (14, 'Bahan Township');
insert into Township (division_id, name) values (14, 'Dagon Township');
insert into Township (division_id, name) values (14, 'Kyauktada Township');
insert into Township (division_id, name) values (14, 'Kyimyindaing Township');
insert into Township (division_id, name) values (14, 'Lanmadaw Township');
insert into Township (division_id, name) values (14, 'Latha Township');
insert into Township (division_id, name) values (14, 'Pabedan Township');
insert into Township (division_id, name) values (14, 'Sanchaung Township');
insert into Township (division_id, name) values (14, 'Seikkan Township');
insert into Township (division_id, name) values (14, 'Hlaing Township');
insert into Township (division_id, name) values (14, 'Kamayut Township');
insert into Township (division_id, name) values (14, 'Mayangon Township');

-- Naypyidaw
insert into Township (division_id, name) values (15, 'Ottarathiri Township');
insert into Township (division_id, name) values (15, 'Pobbathiri Township');
insert into Township (division_id, name) values (15, 'Tatkon Township');
insert into Township (division_id, name) values (15, 'Zeyarthiri Township');
insert into Township (division_id, name) values (15, 'Dekkhinathiri Township');
insert into Township (division_id, name) values (15, 'Lewe Township');
insert into Township (division_id, name) values (15, 'Pyinmana Township');
insert into Township (division_id, name) values (15, 'Zabuthiri Township');
